name: nexus_tributario
version: "1.0.0"
config-version: 2

profile: nexus_tributario_databricks

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nexus_tributario:
    staging:
      +materialized: view
      +schema: silver
    marts:
      dimensions:
        +materialized: table
        +schema: gold
      facts:
        +materialized: table
        +schema: gold
      alerts:
        +materialized: table
        +schema: gold

flags:
  use_materialization_v2: true

vars:
  catalog: nexus_tributario_prod
  bronze_schema: bronze
  silver_schema: silver
  gold_schema: gold
